version: '3.4'
name: 'Reservation'
services:
  reservation:
    image: ${DOCKER_REGISTRY-}reservation
    build:
      context: .
      dockerfile: Reservation/Dockerfile
    depends_on:
          - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=Password!123#AzMogaTukISega
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local